This is makeindex, version 2.15 [TeX Live 2013] (kpathsea + Thai support).
Scanning style file ./log.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file log.acn....done (7 entries accepted, 0 rejected).
Sorting entries....done (21 comparisons).
Generating output file log.acr....done (14 lines written, 0 warnings).
Output written in log.acr.
Transcript written in log.alg.
